connexion()
    nuevo_alumno('Frank', 'Merlo')
    nuevo_alumno('David', 'Monsalve')
    nuevo_alumno('Daniela', 'Monsalve')
    nuevo_alumno('Gabriela', 'Cordero')
    nuevo_alumno('Julio', 'Delgado')
    nuevo_alumno('Luis', 'Baez')
    nuevo_alumno('Eduardo', 'Martinez')
    nuevo_alumno('Oscar', 'Brito')